apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: u4rja4ye5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/u4rja4ye5-java-springboot-gitops